"""Fixed amibuous foreign key

Revision ID: bea82e78f7cd
Revises: 
Create Date: 2025-05-05 15:39:57.929282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea82e78f7cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('math_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_choice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_math_problem_correct_choice',  # Explicitly name the foreign key
            'problem_choice',
            ['correct_choice_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('math_problem', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_math_problem_correct_choice',  # Use the same name as in the upgrade
            type_='foreignkey'
        )
        batch_op.drop_column('correct_choice_id')

    # ### end Alembic commands ###
